### ISSUE TITLE
Integrate data on IPCC reference contracts

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/baseline-contracts#2]
Integrate data on climate domains, ecological zones, generic ABGs and AGB growth into IPCC reference contracts.

## Description
[ Medium Difficulty  - Cairo- Low Priority]

Enhance the existing IPCC baseline contracts in the [carbonable-labs/baseline-contracts](https://github.com/carbonable-labs/baseline-contracts/blob/main/src/methodologies/ipcc.cairo) repository by integrating detailed climate domain and ecological zone data for forests of each country using table 4.12 given in the resources. This enhancement should include:

1. **Data Integration:**
   - Add climate domain and ecological zone classifications for forests of various countries. For example:
     - **France**: Temperate -> Temperate continental forest
   - Include generic biomass values for both natural forests and forest plantations within each ecological zone.
   - Incorporate annual above-ground biomass (AGB) growth for natural forests and plantations.

     Example of a database entry:
     ```plaintext
     Table3A14Data {
       volume: 0,
       biomass: 50,
       source: '',
       climate_domain: 'temperate',
       ecological_zone: 'temperate continental forest',
       AGB_old: 120,
       AGB_new: 100,
       AGB_old_growth: 4,
       AGB_new_growth: 4
     }
     ```

2. **Function Development:**
   - Implement a function that accepts the following inputs:
     - Country
     - Duration of the project (in year)
     - Type of forest (old or new)
   - The function should output the average AGB, utilizing the integrated database.

## Implementation Steps

1. Extend the data schema to include fields for climate domain, ecological zone, and biomass values.
2. Populate the database with the above data for relevant countries and forest types.
3. Develop and test the function to ensure it accurately computes the average AGB based on the inputs provided.

## Additional Information
 Example Function Behavior

The function will:
- Take the `country`, `duration`, and `forest_type` (either 'old' or 'new') as inputs.
- Retrieve the corresponding biomass values (`biomass`, `AGB_old or AGB_new`, `AGB_old_growth or AGB_new_growth`) from the database based on the country and forest type.
- Perform calculations: if old `(biomass + (AGB_old + AGB_old_growth * duration))/2`, if new: `(biomass + (AGB_new + AGB_new_growth * duration))/2` to determine the average AGB over the specified project duration.
Example: I give the function `France`, `20`, `new` --> `(92 + (100 + 4 * 20))/2 --> 136 (output).
- Return the computed average AGB.

## Helpful: 

The current database is based on table [3A.1.4](https://www.ipcc.ch/site/assets/uploads/2018/03/GPG_LULUCF_FULLEN.pdf) (p.206/590)

And here's the table to be added to DB:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGwyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e13d70bde21a48a084869faeb7511ff06537103/image.png" alt="image.png" />

**Note:** Ensure data accuracy and integrity while integrating these values. The function should be robust enough to handle a range of inputs and return meaningful results based on the established database.

---

**Acceptance Criteria**
------------------------------
- [ ] Integrate new data inside the Database
- [ ] Create the function Average AGB
- [ ] Test the function
- [ ] scarb fmt

Feel free to further customize based on specific requirements or additional context.
If you have any questions, please contact: `axelizsak` on telegram`

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by BenFaruna** [comment]
Hello @Khyati729 I would like to work on this issue.

**Comment by axelizsak** [comment]
> Hello @Khyati729 I would like to work on this issue.

Yo, I see that the image of table 4.12 is displayed incorrectly in the registrations here it is: 
<img width="671" alt="Capture d’écran 2024-06-18 à 16 47 39" src="https://github.com/carbonable-labs/baseline-contracts/assets/98711930/10e2b250-08a8-48d3-9ca2-293f7eccf083">

**Comment by BenFaruna** [comment]
Thank you @axelizsak 🙏🏾

**Comment by BenFaruna** [comment]
@Khyati729 I have made a PR on this issue. When you're free you can check it out and let me know if there are some changes you would like to be made.
